add option parsing and usage info

diff --git a/aws-mfa-manager b/aws-mfa-manager
--- a/aws-mfa-manager
+++ b/aws-mfa-manager
@@ -5,68 +5,118 @@
 #
 # GPL 2 or higher
 
-if [ ! -t 0 ]
-then
-  echo Must be on a tty >&2
-  exit 1
-fi
+cmd_setup() {
+  if [ -n "$AWS_SESSION_TOKEN" ]
+  then
+    echo "Session token found.  This can not be used to generate a new token.
+     unset AWS_SESSION_TOKEN AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID
+  and then ensure you have a profile with the normal access key credentials or
+  set the variables to the normal keys.
+  " >&2
+    exit 1
+  fi
 
-if [ -n "$AWS_SESSION_TOKEN" ]
-then
-  echo "Session token found.  This can not be used to generate a new token.
-   unset AWS_SESSION_TOKEN AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID
-and then ensure you have a profile with the normal access key credentials or
-set the variables to the normal keys.
-" >&2
-  exit 1
-fi
+  userarn=$(aws sts get-caller-identity --output text --query Arn)
+  if [ -z "$userarn" ]
+  then
+    echo "Can not identify who you are.  The output of
+    aws sts get-caller-identity --output text --query Arn
+  did not return an ARN." >&2
+    exit 1
+  fi
 
-userarn=$(aws sts get-caller-identity --output text --query Arn)
-if [ -z "$userarn" ]
-then
-  echo "Can not identify who you are.  The output of
-  aws sts get-caller-identity --output text --query Arn
-did not return an ARN." >&2
-  exit 1
-fi
+  username=${userarn##*/}
+  echo You are: $username >&2
 
-username=${userarn##*/}
-echo You are: $username >&2
+  device=$(aws iam list-mfa-devices --user-name "$username" \
+      --output text --query 'MFADevices[0].SerialNumber')
+  if [ -z "$device" ]
+  then
+    echo "Can not find any MFA device for you.  The output of
+    aws iam list-mfa-devices --user-name "$username" \
+      --output text --query 'MFADevices[0].SerialNumber'
+  did not return a serial number." >&2
+    exit 1
+  fi
 
-device=$(aws iam list-mfa-devices --user-name "$username" \
-    --output text --query 'MFADevices[0].SerialNumber')
-if [ -z "$device" ]
-then
-  echo "Can not find any MFA device for you.  The output of
-  aws iam list-mfa-devices --user-name "$username" \
-    --output text --query 'MFADevices[0].SerialNumber'
-did not return a serial number." >&2
-  exit 1
-fi
+  echo Your MFA device is: $device >&2
 
-echo Your MFA device is: $device >&2
+  echo -n "Enter your MFA code now: " >&2
+  read code
 
-echo -n "Enter your MFA code now: " >&2
-read code
+  tokens=$(aws sts get-session-token --serial-number "$device" --token-code $code --output text)
 
-tokens=$(aws sts get-session-token --serial-number "$device" --token-code $code --output text)
+  set -- $tokens
+  access=$2
+  expire=$3
+  secret=$4
+  session=$5
 
-set -- $tokens
-access=$2
-expire=$3
-secret=$4
-session=$5
+  if [ -z "$secret" -o -z "$session" -o -z "$access" ]
+  then
+    echo "Unable to get temporary credentials.  Could not find secret/access/session entries
 
-if [ -z "$secret" -o -z "$session" -o -z "$access" ]
-then
-  echo "Unable to get temporary credentials.  Could not find secret/access/session entries
+  $tokens" >&2
+    exit 1
+  fi
 
-$tokens" >&2
-  exit 1
-fi
+  echo export AWS_SESSION_TOKEN=$session
+  echo export AWS_SECRET_ACCESS_KEY=$secret
+  echo export AWS_ACCESS_KEY_ID=$access
 
-echo export AWS_SESSION_TOKEN=$session
-echo export AWS_SECRET_ACCESS_KEY=$secret
-echo export AWS_ACCESS_KEY_ID=$access
+  echo Keys valid until $expire >&2
+} # cmd_setup()
 
-echo Keys valid until $expire >&2
+show_usage() {
+  cat <<END_OF_USAGE
+Usage: $0 <COMMAND> [<OPTION>...]
+
+Commands:
+  setup                 Obtain MFA credentials.
+  help | usage          Show usage information.
+
+END_OF_USAGE
+}
+
+exit_with_usage() {
+  show_usage >&2
+  exit $1
+}
+
+main() {
+  if [ ! -t 0 ]
+  then
+    echo Must be on a tty >&2
+    exit 1
+  fi
+
+  opt_command=$1
+  shift
+
+  case "$opt_command" in
+    setup)
+      if [ ${1+set} ] ; then
+        echo "unrecognized option \"$1\" for command \"$opt_command\"" >&2
+        exit_with_usage 1
+      fi
+
+      cmd_setup
+      ;;
+
+    help|--help|usage|--usage)
+      if [ ${1+set} ] ; then
+        echo "unrecognized option \"$1\" for command \"$opt_command\"" >&2
+        exit_with_usage 1
+      fi
+
+      exit_with_usage 0
+      ;;
+
+    *)
+      echo "unrecognized command \"$opt_command\"" >&2
+      exit_with_usage 1
+      ;;
+  esac
+}
+
+main "$@"
